# Generated by Django 4.0.5 on 2022-06-19 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='private_key',
            new_name='acc_add',
        ),
        migrations.RenameField(
            model_name='accounts',
            old_name='public_key',
            new_name='pub_key',
        ),
    ]
